/**
 * Tests for build-commands.ts
 * Satisfies: RT-1 (build-time translator), T1 (command format translation), B3 (single canonical source)
 */

import { describe, it, expect, beforeAll, afterAll } from 'bun:test';
import { mkdirSync, writeFileSync, readFileSync, readdirSync, rmSync, existsSync } from 'fs';
import { join } from 'path';
import { buildCommands } from '../../install/lib/build-commands';

const TEST_DIR = join(import.meta.dir, '__fixtures__', 'build-commands');
const SOURCE_DIR = join(TEST_DIR, 'source');
const GEMINI_OUT = join(TEST_DIR, 'gemini');
const CODEX_OUT = join(TEST_DIR, 'codex');

beforeAll(() => {
  // Create test fixtures
  mkdirSync(SOURCE_DIR, { recursive: true });

  // Canonical command with frontmatter
  writeFileSync(join(SOURCE_DIR, 'm0-init.md'), `---
description: "Initialize a new constraint manifold"
argument-hint: "<feature-name>"
---
# Initialize Manifold

Create a new constraint manifold for the given feature.

## Steps
1. Create .manifold/<feature>.json
2. Create .manifold/<feature>.md
3. Set phase to INITIALIZED
`);

  // Command without argument-hint
  writeFileSync(join(SOURCE_DIR, 'm-status.md'), `---
description: "Show current manifold state"
---
# Manifold Status

Display the current state of all manifolds in this project.
`);

  // Parallel command (non-m prefix)
  writeFileSync(join(SOURCE_DIR, 'parallel.md'), `---
description: "Execute tasks in parallel worktrees"
argument-hint: "task1 task2 [--dry-run]"
---
# Parallel Execution

Run multiple tasks concurrently using git worktrees.
`);

  // Non-command file (should be skipped)
  writeFileSync(join(SOURCE_DIR, 'SCHEMA_REFERENCE.md'), `---
description: "Schema reference documentation"
---
# Schema Reference
This is documentation, not a command.
`);
});

afterAll(() => {
  rmSync(TEST_DIR, { recursive: true, force: true });
});

describe('buildCommands', () => {
  it('generates correct number of Gemini and Codex outputs', () => {
    const { geminiCount, codexCount } = buildCommands(SOURCE_DIR, GEMINI_OUT, CODEX_OUT);

    // Should generate for m0-init, m-status, parallel (skip SCHEMA_REFERENCE)
    expect(geminiCount).toBe(3);
    expect(codexCount).toBe(3);
  });

  it('creates Gemini .toml files with correct format', () => {
    const tomlContent = readFileSync(join(GEMINI_OUT, 'm0-init.toml'), 'utf-8');

    // Should have auto-generated header
    expect(tomlContent).toContain('Auto-generated by build-commands.ts');

    // Should have description
    expect(tomlContent).toContain('description = "Initialize a new constraint manifold"');

    // Should have argument_hint
    expect(tomlContent).toContain('argument_hint = "<feature-name>"');

    // Should have prompt with triple quotes
    expect(tomlContent).toContain('prompt = """');
    expect(tomlContent).toContain('# Initialize Manifold');
  });

  it('omits argument_hint when not present in source', () => {
    const tomlContent = readFileSync(join(GEMINI_OUT, 'm-status.toml'), 'utf-8');

    expect(tomlContent).not.toContain('argument_hint');
    expect(tomlContent).toContain('description = "Show current manifold state"');
  });

  it('creates Codex SKILL.md directories with correct format', () => {
    const skillDir = join(CODEX_OUT, 'manifold-m0-init');
    expect(existsSync(skillDir)).toBe(true);

    const skillContent = readFileSync(join(skillDir, 'SKILL.md'), 'utf-8');

    // Should have name and description metadata
    expect(skillContent).toContain('name: manifold-m0-init');
    expect(skillContent).toContain('description: "Initialize a new constraint manifold"');

    // Should have command body
    expect(skillContent).toContain('# /manifold:m0-init');
    expect(skillContent).toContain('# Initialize Manifold');
  });

  it('handles parallel command (non-m prefix)', () => {
    // Gemini
    expect(existsSync(join(GEMINI_OUT, 'parallel.toml'))).toBe(true);
    const toml = readFileSync(join(GEMINI_OUT, 'parallel.toml'), 'utf-8');
    expect(toml).toContain('description = "Execute tasks in parallel worktrees"');

    // Codex
    const skillDir = join(CODEX_OUT, 'manifold-parallel');
    expect(existsSync(join(skillDir, 'SKILL.md'))).toBe(true);
  });

  it('skips non-command files like SCHEMA_REFERENCE', () => {
    expect(existsSync(join(GEMINI_OUT, 'SCHEMA_REFERENCE.toml'))).toBe(false);

    const codexDirs = readdirSync(CODEX_OUT);
    expect(codexDirs).not.toContain('manifold-SCHEMA_REFERENCE');
  });

  it('is idempotent (running twice produces same result)', () => {
    const { geminiCount: count1 } = buildCommands(SOURCE_DIR, GEMINI_OUT, CODEX_OUT);
    const content1 = readFileSync(join(GEMINI_OUT, 'm0-init.toml'), 'utf-8');

    const { geminiCount: count2 } = buildCommands(SOURCE_DIR, GEMINI_OUT, CODEX_OUT);
    const content2 = readFileSync(join(GEMINI_OUT, 'm0-init.toml'), 'utf-8');

    expect(count1).toBe(count2);
    expect(content1).toBe(content2);
  });
});

describe('TOML escaping', () => {
  it('handles special characters in command body', () => {
    // Create a command with special characters
    writeFileSync(join(SOURCE_DIR, 'm-special.md'), `---
description: "Test special chars"
---
# Special Characters

Use backslash \\ and triple quotes """ carefully.
Also handles "double quotes" inside body.
`);

    buildCommands(SOURCE_DIR, GEMINI_OUT, CODEX_OUT);

    const toml = readFileSync(join(GEMINI_OUT, 'm-special.toml'), 'utf-8');
    // Backslashes should be escaped
    expect(toml).toContain('\\\\');
  });
});
