#!/usr/bin/env bun
/**
 * Build-time Command Translator
 * Satisfies: RT-1 (build-time translator), T1 (command format translation), B3 (single canonical source)
 *
 * Translates canonical .md commands (with YAML frontmatter) into:
 * - Gemini CLI: .toml files in install/agents/gemini/commands/
 * - Codex CLI: SKILL.md files in install/agents/codex/skills/manifold-<cmd>/
 * - Codex plugin: command markdown + bundled skills in plugins/manifold-codex/
 *
 * Claude Code and AMP receive the canonical .md files directly (no translation).
 *
 * Usage: bun run install/lib/build-commands.ts [--verify]
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, basename, parse as parsePath } from 'path';

// ============================================================
// Types
// ============================================================

interface CommandMeta {
  description: string;
  'argument-hint'?: string;
  'model-routing'?: string;
}

interface ParsedCommand {
  meta: CommandMeta;
  body: string;
  filename: string;
  commandName: string;
}

// ============================================================
// Parser: Extract YAML frontmatter from canonical .md
// ============================================================

function parseFrontmatter(content: string): { meta: Record<string, string>; body: string } {
  const fmMatch = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!fmMatch) {
    return { meta: {}, body: content };
  }

  const meta: Record<string, string> = {};
  for (const line of fmMatch[1].split('\n')) {
    const colonIdx = line.indexOf(':');
    if (colonIdx > 0) {
      const key = line.slice(0, colonIdx).trim();
      let value = line.slice(colonIdx + 1).trim();
      // Strip surrounding quotes
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
        // Unescape YAML double-quoted string escapes
        value = value.replace(/\\"/g, '"').replace(/\\\\/g, '\\');
      }
      meta[key] = value;
    }
  }

  return { meta, body: fmMatch[2] };
}

function parseCanonicalCommand(filepath: string): ParsedCommand {
  const content = readFileSync(filepath, 'utf-8');
  const { meta, body } = parseFrontmatter(content);
  const filename = basename(filepath);
  const commandName = parsePath(filepath).name; // e.g., "m0-init"

  return {
    meta: {
      description: meta.description || `Manifold ${commandName} command`,
      'argument-hint': meta['argument-hint'],
      'model-routing': meta['model-routing'],
    },
    body,
    filename,
    commandName,
  };
}

// ============================================================
// Gemini: Emit .toml command files
// ============================================================

function escapeTomlString(s: string): string {
  // For multi-line strings, use triple-quoted TOML literals
  return s.replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"');
}

function toGeminiToml(cmd: ParsedCommand): string {
  const desc = cmd.meta.description.replace(/"/g, '\\"');
  const argHint = cmd.meta['argument-hint']
    ? `\nargument_hint = "${cmd.meta['argument-hint'].replace(/"/g, '\\"')}"`
    : '';

  // Gemini custom commands use prompt (required) and description (optional)
  const prompt = cmd.body.trim();

  return `# Manifold command: /manifold:${cmd.commandName}
# Auto-generated by build-commands.ts — do not edit manually
# Satisfies: T1 (command format translation), B3 (single canonical source)

description = "${desc}"${argHint}
prompt = """
${escapeTomlString(prompt)}
"""
`;
}

function writeGeminiCommands(commands: ParsedCommand[], outDir: string): number {
  mkdirSync(outDir, { recursive: true });
  let count = 0;
  for (const cmd of commands) {
    // Skip non-command files like SCHEMA_REFERENCE.md
    if (!cmd.commandName.startsWith('m') && cmd.commandName !== 'parallel') continue;

    const toml = toGeminiToml(cmd);
    const outPath = join(outDir, `${cmd.commandName}.toml`);
    writeFileSync(outPath, toml, 'utf-8');
    count++;
  }
  return count;
}

// ============================================================
// Codex: Emit SKILL.md skill directories
// ============================================================

const CODEX_AGENT_MAP: Record<string, { agentName: string; model: string; reasoning: string }> = {
  'm0-init': {
    agentName: 'manifold_m0_init_worker',
    model: 'gpt-5.4-mini',
    reasoning: 'low',
  },
  'm-status': {
    agentName: 'manifold_m_status_worker',
    model: 'gpt-5.4-mini',
    reasoning: 'low',
  },
  'm-solve': {
    agentName: 'manifold_m_solve_worker',
    model: 'gpt-5.4-mini',
    reasoning: 'medium',
  },
  'm4-generate': {
    agentName: 'manifold_m4_generate_worker',
    model: 'gpt-5.4',
    reasoning: 'high',
  },
  'm5-verify': {
    agentName: 'manifold_m5_verify_worker',
    model: 'gpt-5.4-mini',
    reasoning: 'medium',
  },
  'm6-integrate': {
    agentName: 'manifold_m6_integrate_worker',
    model: 'gpt-5.4-mini',
    reasoning: 'medium',
  },
};

function toCodexAgentName(claudeWorkerName: string): string {
  return claudeWorkerName
    .replace(/^manifold:/, 'manifold_')
    .replace(/-/g, '_');
}

function rewriteForCodexSkill(cmd: ParsedCommand, content: string): string {
  const route = CODEX_AGENT_MAP[cmd.commandName];
  if (!route) return content;

  let rewritten = content;
  rewritten = rewritten.replace(
    'Dispatch using the Agent tool.',
    `Dispatch using the Codex subagent system. Prefer the custom agent \`${route.agentName}\` configured for \`${route.model}\` with \`${route.reasoning}\` reasoning.`,
  );
  rewritten = rewritten.replace(
    /Spawn an Agent with:/g,
    'Spawn a Codex subagent with:',
  );
  rewritten = rewritten.replace(
    /`subagent_type`:\s*`?"([^"]+)"`?/g,
    (_match, agentType) => `\`agent\`: \`${toCodexAgentName(agentType)}\``,
  );
  rewritten = rewritten.replace(
    /`model`:\s*`?"([^"]+)"`?/g,
    `\`model\`: \`${route.model}\`\n   - \`reasoning_effort\`: \`${route.reasoning}\``,
  );
  rewritten = rewritten.replace(
    /Return the agent's result to the user verbatim/g,
    "Return the subagent's result to the user verbatim",
  );
  rewritten = rewritten.replace(
    /Agent\(/g,
    'spawn_agent(',
  );
  rewritten = rewritten.replace(
    /subagent_type:\s*"([^"]+)"/g,
    (_match, agentType) => `agent: "${toCodexAgentName(agentType)}"`,
  );
  rewritten = rewritten.replace(
    /model:\s*"([^"]+)"/g,
    `model: "${route.model}",\n  reasoning_effort: "${route.reasoning}"`,
  );

  return rewritten;
}

function toCodexSkillMd(cmd: ParsedCommand): string {
  // Codex SKILL.md uses name + description metadata at the top,
  // followed by the skill content as markdown instructions
  const name = `manifold-${cmd.commandName}`;
  // Quote description to avoid YAML parsing issues with colons
  const desc = cmd.meta.description.replace(/"/g, '\\"');
  const body = rewriteForCodexSkill(cmd, cmd.body.trim());

  return `---
name: ${name}
description: "${desc}"
---

# /manifold:${cmd.commandName}

${body}
`;
}

function writeCodexSkills(commands: ParsedCommand[], outDir: string): number {
  mkdirSync(outDir, { recursive: true });
  let count = 0;
  for (const cmd of commands) {
    if (!cmd.commandName.startsWith('m') && cmd.commandName !== 'parallel') continue;

    const skillDir = join(outDir, `manifold-${cmd.commandName}`);
    mkdirSync(skillDir, { recursive: true });

    const skillMd = toCodexSkillMd(cmd);
    writeFileSync(join(skillDir, 'SKILL.md'), skillMd, 'utf-8');
    count++;
  }
  return count;
}

// ============================================================
// Codex plugin: emit command markdown + bundled skills
// ============================================================

function toCodexPluginCommand(cmd: ParsedCommand): string {
  return rewriteForCodexSkill(cmd, cmd.body.trim()) + '\n';
}

function writeCodexPluginCommands(commands: ParsedCommand[], outDir: string): number {
  mkdirSync(outDir, { recursive: true });
  let count = 0;
  for (const cmd of commands) {
    if (!cmd.commandName.startsWith('m') && cmd.commandName !== 'parallel') continue;

    const commandMd = toCodexPluginCommand(cmd);
    writeFileSync(join(outDir, `${cmd.commandName}.md`), commandMd, 'utf-8');
    count++;
  }
  return count;
}

function writeCodexPluginSkills(commands: ParsedCommand[], outDir: string): number {
  return writeCodexSkills(commands, outDir);
}

// ============================================================
// Verification mode
// ============================================================

function verifyOutputs(
  geminiDir: string,
  codexDir: string,
  codexPluginCommandsDir: string,
  codexPluginSkillsDir: string,
  expectedCount: number,
): boolean {
  let ok = true;

  // Check Gemini .toml files
  if (!existsSync(geminiDir)) {
    console.error(`✗ Gemini output directory missing: ${geminiDir}`);
    ok = false;
  } else {
    const tomlFiles = readdirSync(geminiDir).filter(f => f.endsWith('.toml'));
    if (tomlFiles.length !== expectedCount) {
      console.error(`✗ Expected ${expectedCount} Gemini .toml files, found ${tomlFiles.length}`);
      ok = false;
    } else {
      console.log(`✓ ${tomlFiles.length} Gemini .toml files`);
    }
  }

  // Check Codex SKILL.md directories
  if (!existsSync(codexDir)) {
    console.error(`✗ Codex output directory missing: ${codexDir}`);
    ok = false;
  } else {
    // Count only command-derived skills (exclude manually-created manifold-context, manifold-suggest)
    const skillDirs = readdirSync(codexDir).filter(d =>
      existsSync(join(codexDir, d, 'SKILL.md'))
    );
    const commandSkillDirs = skillDirs.filter(d =>
      d.startsWith('manifold-m') || d === 'manifold-parallel'
    );
    if (commandSkillDirs.length !== expectedCount) {
      console.error(`✗ Expected ${expectedCount} Codex command skill dirs, found ${commandSkillDirs.length}`);
      ok = false;
    } else {
      console.log(`✓ ${commandSkillDirs.length} Codex command skill directories (${skillDirs.length} total with hook skills)`);
    }
  }

  if (!existsSync(codexPluginCommandsDir)) {
    console.error(`✗ Codex plugin commands directory missing: ${codexPluginCommandsDir}`);
    ok = false;
  } else {
    const commandFiles = readdirSync(codexPluginCommandsDir).filter(f => f.endsWith('.md'));
    if (commandFiles.length !== expectedCount) {
      console.error(`✗ Expected ${expectedCount} Codex plugin command files, found ${commandFiles.length}`);
      ok = false;
    } else {
      console.log(`✓ ${commandFiles.length} Codex plugin command files`);
    }
  }

  if (!existsSync(codexPluginSkillsDir)) {
    console.error(`✗ Codex plugin skills directory missing: ${codexPluginSkillsDir}`);
    ok = false;
  } else {
    const skillDirs = readdirSync(codexPluginSkillsDir).filter(d =>
      existsSync(join(codexPluginSkillsDir, d, 'SKILL.md'))
    );
    if (skillDirs.length !== expectedCount) {
      console.error(`✗ Expected ${expectedCount} Codex plugin skill dirs, found ${skillDirs.length}`);
      ok = false;
    } else {
      console.log(`✓ ${skillDirs.length} Codex plugin skill directories`);
    }
  }

  return ok;
}

// ============================================================
// Main
// ============================================================

export function buildCommands(
  sourceDir: string,
  geminiOutDir: string,
  codexOutDir: string,
  codexPluginCommandsDir: string,
  codexPluginSkillsDir: string,
): { geminiCount: number; codexCount: number; codexPluginCommandCount: number; codexPluginSkillCount: number } {
  // Read all canonical .md commands
  const mdFiles = readdirSync(sourceDir)
    .filter(f => f.endsWith('.md'))
    .map(f => join(sourceDir, f));

  const commands = mdFiles.map(parseCanonicalCommand);

  // Generate Gemini .toml files
  const geminiCount = writeGeminiCommands(commands, geminiOutDir);

  // Generate Codex SKILL.md directories
  const codexCount = writeCodexSkills(commands, codexOutDir);

  // Generate Codex plugin command markdown + bundled skills
  const codexPluginCommandCount = writeCodexPluginCommands(commands, codexPluginCommandsDir);
  const codexPluginSkillCount = writeCodexPluginSkills(commands, codexPluginSkillsDir);

  return { geminiCount, codexCount, codexPluginCommandCount, codexPluginSkillCount };
}

// CLI entry point
if (import.meta.main) {
  const projectRoot = join(import.meta.dir, '..', '..');
  const sourceDir = join(projectRoot, 'install', 'commands');
  const geminiOutDir = join(projectRoot, 'install', 'agents', 'gemini', 'commands');
  const codexOutDir = join(projectRoot, 'install', 'agents', 'codex', 'skills');
  const codexPluginCommandsDir = join(projectRoot, 'plugins', 'manifold-codex', 'commands');
  const codexPluginSkillsDir = join(projectRoot, 'plugins', 'manifold-codex', 'skills');

  const isVerify = process.argv.includes('--verify');

  if (isVerify) {
    // Count expected command files (m* + parallel, excluding SCHEMA_*)
    const expectedCount = readdirSync(sourceDir)
      .filter(f => f.endsWith('.md'))
      .filter(f => {
        const name = parsePath(f).name;
        return name.startsWith('m') || name === 'parallel';
      })
      .length;

    const ok = verifyOutputs(
      geminiOutDir,
      codexOutDir,
      codexPluginCommandsDir,
      codexPluginSkillsDir,
      expectedCount,
    );
    process.exit(ok ? 0 : 1);
  }

  console.log('Building agent-specific command files...');
  console.log(`  Source: ${sourceDir}`);

  const {
    geminiCount,
    codexCount,
    codexPluginCommandCount,
    codexPluginSkillCount,
  } = buildCommands(
    sourceDir,
    geminiOutDir,
    codexOutDir,
    codexPluginCommandsDir,
    codexPluginSkillsDir,
  );

  console.log(`  ✓ Gemini CLI: ${geminiCount} .toml files → ${geminiOutDir}`);
  console.log(`  ✓ Codex CLI:  ${codexCount} SKILL.md dirs → ${codexOutDir}`);
  console.log(`  ✓ Codex plugin: ${codexPluginCommandCount} commands → ${codexPluginCommandsDir}`);
  console.log(`  ✓ Codex plugin: ${codexPluginSkillCount} skills → ${codexPluginSkillsDir}`);
  console.log('Done.');
}
