#!/usr/bin/env bash
#
# Manifold Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/dhanesh/manifold/main/install/install.sh | bash
#
# Installs Manifold for Claude Code and/or AMP
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Manifold info
REPO="https://raw.githubusercontent.com/dhanesh/manifold/main"
RELEASES="https://github.com/dhanesh/manifold/releases/download"
FALLBACK_VERSION="2.2.1"

# Fetch latest version from GitHub API (falls back to hardcoded if API unavailable)
get_latest_version() {
    local version
    version=$(curl -fsSL "https://api.github.com/repos/dhanesh/manifold/releases/latest" 2>/dev/null | grep '"tag_name"' | sed -E 's/.*"v?([^"]+)".*/\1/')
    if [ -z "$version" ]; then
        echo "$FALLBACK_VERSION"
    else
        echo "$version"
    fi
}

VERSION=$(get_latest_version)
CLI_VERSION="$VERSION"

print_banner() {
    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║${NC}  ${BOLD}Manifold${NC} v${VERSION}                                      ${CYAN}║${NC}"
    echo -e "${CYAN}║${NC}  Constraint-first development framework               ${CYAN}║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

print_step() {
    echo -e "${BLUE}▶${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

# Detect OS and architecture
detect_platform() {
    local os=""
    local arch=""

    case "$(uname -s)" in
        Darwin) os="darwin" ;;
        Linux) os="linux" ;;
        *) os="unsupported" ;;
    esac

    case "$(uname -m)" in
        x86_64|amd64) arch="x64" ;;
        arm64|aarch64) arch="arm64" ;;
        *) arch="unsupported" ;;
    esac

    echo "${os}-${arch}"
}

# Download and install CLI binary
install_cli() {
    local platform="$1"
    local install_dir="${2:-/usr/local/bin}"

    if [[ "$platform" == *"unsupported"* ]]; then
        print_warning "CLI binary not available for this platform: $platform"
        print_warning "You can build from source: cd cli && bun run compile"
        return 1
    fi

    local binary_name="manifold-${platform}"
    local download_url="${RELEASES}/v${CLI_VERSION}/${binary_name}"
    local tmp_file="/tmp/manifold-cli-$$"

    print_step "Downloading CLI binary for ${platform}..."

    if curl -fsSL "$download_url" -o "$tmp_file" 2>/dev/null; then
        chmod +x "$tmp_file"

        # Try to install to system path, fall back to local
        if [[ -w "$install_dir" ]] || sudo -n true 2>/dev/null; then
            if [[ -w "$install_dir" ]]; then
                mv "$tmp_file" "$install_dir/manifold"
            else
                sudo mv "$tmp_file" "$install_dir/manifold"
            fi
            print_success "CLI installed to $install_dir/manifold"
            return 0
        else
            # Fall back to ~/.local/bin
            local local_bin="$HOME/.local/bin"
            mkdir -p "$local_bin"
            mv "$tmp_file" "$local_bin/manifold"
            print_success "CLI installed to $local_bin/manifold"
            print_warning "Add $local_bin to your PATH if not already present"
            return 0
        fi
    else
        print_warning "CLI binary not yet available (release pending)"
        print_warning "You can build from source: cd cli && bun run compile"
        rm -f "$tmp_file"
        return 1
    fi
}

# Detect Claude Code
detect_claude_code() {
    if [[ -d "$HOME/.claude" ]]; then
        echo "$HOME/.claude"
        return 0
    fi
    return 1
}

# Detect AMP
detect_amp() {
    if command -v amp &> /dev/null; then
        echo "$HOME/.amp"
        return 0
    fi
    return 1
}

# Detect Gemini CLI
# Satisfies: RT-2 (agent detection), T2 (Gemini CLI support)
detect_gemini() {
    if command -v gemini &> /dev/null || [[ -d "$HOME/.gemini" ]]; then
        echo "$HOME/.gemini"
        return 0
    fi
    return 1
}

# Detect Codex CLI
# Satisfies: RT-2 (agent detection), T2 (Codex CLI support)
detect_codex() {
    if command -v codex &> /dev/null || [[ -d "$HOME/.codex" ]]; then
        echo "$HOME/.codex"
        return 0
    fi
    return 1
}

# Command files to install (individual slash commands)
# Canonical .md source — Claude Code and AMP receive these directly
COMMAND_FILES=(
    "m0-init.md"
    "m1-constrain.md"
    "m2-tension.md"
    "m3-anchor.md"
    "m4-generate.md"
    "m5-verify.md"
    "m6-integrate.md"
    "m-status.md"
    "m-solve.md"
    "m-quick.md"
    "parallel.md"
    "SCHEMA_REFERENCE.md"
)

# Pre-built Gemini .toml command files (generated by build-commands.ts)
# Satisfies: RT-1 (build-time translation), T1 (command format translation)
GEMINI_COMMAND_DIR="agents/gemini/commands"

# Pre-built Codex SKILL.md skill directories (generated by build-commands.ts)
# Satisfies: RT-1 (build-time translation), T1 (command format translation)
CODEX_SKILLS_DIR="agents/codex/skills"

# Parallel library files to install
PARALLEL_LIB_FILES=(
    "task-analyzer.ts"
    "file-predictor.ts"
    "overlap-detector.ts"
    "parallel-config.ts"
    "worktree-manager.ts"
    "resource-monitor.ts"
    "merge-orchestrator.ts"
    "parallel-executor.ts"
    "progress-reporter.ts"
    "command.ts"
    "index.ts"
)

# Inject schema reference into the agent's instruction file
# This ensures schema values are retained across context compaction
# Version-aware: updates if schema version changes
# Satisfies: RT-7 (instruction file injection), B2 (consistent developer experience)
inject_schema_reference() {
    local base_dir="$1"
    local instruction_file="${2:-CLAUDE.md}"
    local claude_md="$base_dir/$instruction_file"
    local marker="# Manifold Schema Quick Reference"
    local version_pattern="MANIFOLD_SCHEMA_VERSION:"

    # Get schema snippet
    local snippet=""
    if [[ -n "$LOCAL_INSTALL" ]]; then
        snippet=$(cat "$SCRIPT_DIR/SCHEMA_SNIPPET.md")
    else
        snippet=$(curl -fsSL "$REPO/install/SCHEMA_SNIPPET.md" 2>/dev/null)
    fi

    if [[ -z "$snippet" ]]; then
        print_warning "Could not fetch schema snippet"
        return 1
    fi

    # Extract new version from snippet
    local new_version
    new_version=$(echo "$snippet" | grep -o "${version_pattern}[0-9]*" | grep -o '[0-9]*')
    if [[ -z "$new_version" ]]; then
        new_version="0"
    fi

    # Check if already injected and compare versions
    if [[ -f "$claude_md" ]] && grep -q "$marker" "$claude_md" 2>/dev/null; then
        local existing_version
        existing_version=$(grep -o "${version_pattern}[0-9]*" "$claude_md" 2>/dev/null | grep -o '[0-9]*' | head -1)
        if [[ -z "$existing_version" ]]; then
            existing_version="0"
        fi

        if [[ "$existing_version" -ge "$new_version" ]]; then
            print_success "Schema reference v$existing_version already in CLAUDE.md (up to date)"
            return 0
        fi

        # Remove old schema section before adding new one
        print_step "Updating schema reference v$existing_version -> v$new_version..."

        # Create temp file without old schema section
        # Pattern: from "# Manifold Schema Quick Reference" to next "# " heading or EOF
        local tmp_file="/tmp/claude_md_$$"
        awk -v marker="$marker" '
            BEGIN { skip = 0 }
            $0 ~ marker { skip = 1; next }
            skip && /^# [^M]/ { skip = 0 }
            skip && /^# Manifold/ { next }
            !skip { print }
        ' "$claude_md" > "$tmp_file"
        mv "$tmp_file" "$claude_md"
    fi

    # Create or append to CLAUDE.md
    if [[ ! -f "$claude_md" ]]; then
        echo "$snippet" > "$claude_md"
        print_success "Created CLAUDE.md with Manifold schema reference v$new_version"
    else
        # Append with separator
        echo "" >> "$claude_md"
        echo "$snippet" >> "$claude_md"
        print_success "Added Manifold schema reference v$new_version to CLAUDE.md"
    fi
}

# Install Manifold for Claude Code or AMP (native .md commands)
# Satisfies: RT-3 (per-agent installation), B1 (all 4 agents)
install_manifold_native() {
    local base_dir="$1"
    local agent_name="$2"
    local instruction_file="${3:-CLAUDE.md}"

    print_step "Installing Manifold to $agent_name..."

    local skills_dir="$base_dir/skills"
    local commands_dir="$base_dir/commands"
    local hooks_dir="$base_dir/hooks"
    local lib_dir="$base_dir/lib"

    # Create directories
    mkdir -p "$skills_dir/manifold"
    mkdir -p "$commands_dir"
    mkdir -p "$hooks_dir"
    mkdir -p "$lib_dir/parallel"

    # Install skill (for /manifold overview command)
    if [[ -n "$LOCAL_INSTALL" ]]; then
        cp "$SCRIPT_DIR/manifold/SKILL.md" "$skills_dir/manifold/SKILL.md"
    else
        curl -fsSL "$REPO/install/manifold/SKILL.md" -o "$skills_dir/manifold/SKILL.md"
    fi
    print_success "Installed /manifold skill to $skills_dir/manifold/"

    # Install commands (for /manifold:m0-init, /manifold:m1-constrain, etc.)
    for cmd_file in "${COMMAND_FILES[@]}"; do
        if [[ -n "$LOCAL_INSTALL" ]]; then
            cp "$SCRIPT_DIR/commands/$cmd_file" "$commands_dir/$cmd_file"
        else
            curl -fsSL "$REPO/install/commands/$cmd_file" -o "$commands_dir/$cmd_file"
        fi
    done
    print_success "Installed ${#COMMAND_FILES[@]} commands to $commands_dir/"

    # Install parallel library (for /manifold:parallel command)
    for lib_file in "${PARALLEL_LIB_FILES[@]}"; do
        if [[ -n "$LOCAL_INSTALL" ]]; then
            cp "$SCRIPT_DIR/lib/parallel/$lib_file" "$lib_dir/parallel/$lib_file"
        else
            curl -fsSL "$REPO/install/lib/parallel/$lib_file" -o "$lib_dir/parallel/$lib_file"
        fi
    done
    print_success "Installed parallel library to $lib_dir/parallel/"

    # Install hooks (for context preservation and auto-suggest)
    if [[ -n "$LOCAL_INSTALL" ]]; then
        cp "$SCRIPT_DIR/hooks/manifold-context.ts" "$hooks_dir/manifold-context.ts"
        cp "$SCRIPT_DIR/hooks/auto-suggester.ts" "$hooks_dir/auto-suggester.ts"
    else
        curl -fsSL "$REPO/install/hooks/manifold-context.ts" -o "$hooks_dir/manifold-context.ts"
        curl -fsSL "$REPO/install/hooks/auto-suggester.ts" -o "$hooks_dir/auto-suggester.ts"
    fi
    print_success "Installed hooks to $hooks_dir/"

    # Inject schema reference into instruction file for context retention
    inject_schema_reference "$base_dir" "$instruction_file"
}

# Install Manifold for Gemini CLI (translated .toml commands)
# Satisfies: RT-3 (per-agent installation), T1 (command format translation), T2 (Gemini support)
install_manifold_gemini() {
    local base_dir="$1"

    print_step "Installing Manifold to Gemini CLI..."

    local commands_dir="$base_dir/commands"
    local hooks_dir="$base_dir/hooks"

    mkdir -p "$commands_dir"
    mkdir -p "$hooks_dir"

    # Install pre-built .toml commands (generated by build-commands.ts)
    local toml_count=0
    if [[ -n "$LOCAL_INSTALL" ]]; then
        if [[ -d "$SCRIPT_DIR/$GEMINI_COMMAND_DIR" ]]; then
            for toml_file in "$SCRIPT_DIR/$GEMINI_COMMAND_DIR"/*.toml; do
                [[ -f "$toml_file" ]] || continue
                cp "$toml_file" "$commands_dir/$(basename "$toml_file")"
                ((toml_count++))
            done
        fi
    else
        # Download pre-built .toml files from repo
        for cmd_file in "${COMMAND_FILES[@]}"; do
            local cmd_name="${cmd_file%.md}"
            # Skip non-command files
            [[ "$cmd_name" == SCHEMA_REFERENCE ]] && continue
            local toml_url="$REPO/install/$GEMINI_COMMAND_DIR/${cmd_name}.toml"
            if curl -fsSL "$toml_url" -o "$commands_dir/${cmd_name}.toml" 2>/dev/null; then
                ((toml_count++))
            fi
        done
    fi
    print_success "Installed $toml_count Gemini .toml commands to $commands_dir/"

    # Install Gemini-specific hooks
    if [[ -n "$LOCAL_INSTALL" ]]; then
        if [[ -f "$SCRIPT_DIR/agents/gemini/hooks/manifold-context.ts" ]]; then
            cp "$SCRIPT_DIR/agents/gemini/hooks/manifold-context.ts" "$hooks_dir/manifold-context.ts"
        fi
    else
        curl -fsSL "$REPO/install/agents/gemini/hooks/manifold-context.ts" -o "$hooks_dir/manifold-context.ts" 2>/dev/null || true
    fi
    print_success "Installed hooks to $hooks_dir/"

    # Install parallel library bundle (Node.js-compatible)
    # Satisfies: RT-8 (parallel library portability), T7 (Node.js bundle), B1 (feature parity)
    local lib_dir="$base_dir/lib/parallel"
    mkdir -p "$lib_dir"
    if [[ -n "$LOCAL_INSTALL" ]]; then
        if [[ -f "$SCRIPT_DIR/lib/parallel/parallel.bundle.js" ]]; then
            cp "$SCRIPT_DIR/lib/parallel/parallel.bundle.js" "$lib_dir/parallel.bundle.js"
            print_success "Installed parallel library bundle to $lib_dir/"
        fi
    else
        curl -fsSL "$REPO/install/lib/parallel/parallel.bundle.js" \
            -o "$lib_dir/parallel.bundle.js" 2>/dev/null && \
            print_success "Installed parallel library bundle to $lib_dir/" || true
    fi

    # Merge Manifold config into Gemini settings.json
    # Satisfies: RT-6 (idempotent configuration)
    local settings_path="$base_dir/settings.json"
    if command -v bun &> /dev/null; then
        if [[ -n "$LOCAL_INSTALL" ]]; then
            bun run "$SCRIPT_DIR/lib/config-merger.ts" gemini "$settings_path" 2>/dev/null || true
        fi
    fi

    # Inject schema reference into GEMINI.md
    inject_schema_reference "$base_dir" "GEMINI.md"
}

# Install Manifold for Codex CLI (translated SKILL.md files)
# Satisfies: RT-3 (per-agent installation), T1 (command format translation), T2 (Codex support)
install_manifold_codex() {
    local base_dir="$1"

    print_step "Installing Manifold to Codex CLI..."

    # Codex uses two directories: ~/.codex/ for config and ~/.agents/skills/ for skills
    # Satisfies: TN5 (two-directory split)
    local codex_config_dir="$base_dir"
    local skills_base_dir="$HOME/.agents/skills"

    mkdir -p "$codex_config_dir"
    mkdir -p "$skills_base_dir"

    # Install pre-built SKILL.md skill directories (generated by build-commands.ts)
    local skill_count=0
    if [[ -n "$LOCAL_INSTALL" ]]; then
        if [[ -d "$SCRIPT_DIR/$CODEX_SKILLS_DIR" ]]; then
            for skill_dir in "$SCRIPT_DIR/$CODEX_SKILLS_DIR"/manifold-*; do
                [[ -d "$skill_dir" ]] || continue
                local dirname
                dirname=$(basename "$skill_dir")
                mkdir -p "$skills_base_dir/$dirname"
                cp "$skill_dir/SKILL.md" "$skills_base_dir/$dirname/SKILL.md"
                ((skill_count++))
            done
        fi
    else
        # Download pre-built SKILL.md files from repo
        for cmd_file in "${COMMAND_FILES[@]}"; do
            local cmd_name="${cmd_file%.md}"
            [[ "$cmd_name" == SCHEMA_REFERENCE ]] && continue
            local skill_url="$REPO/install/$CODEX_SKILLS_DIR/manifold-${cmd_name}/SKILL.md"
            mkdir -p "$skills_base_dir/manifold-${cmd_name}"
            if curl -fsSL "$skill_url" -o "$skills_base_dir/manifold-${cmd_name}/SKILL.md" 2>/dev/null; then
                ((skill_count++))
            fi
        done
    fi
    print_success "Installed $skill_count Codex skills to $skills_base_dir/"

    # Install Codex skills-as-hooks (context preservation and auto-suggest)
    # Satisfies: RT-4 (Codex hooks via skills), TN1 (skills-as-hooks)
    local hook_skills=("manifold-context" "manifold-suggest")
    for hook_skill in "${hook_skills[@]}"; do
        mkdir -p "$skills_base_dir/$hook_skill"
        if [[ -n "$LOCAL_INSTALL" ]]; then
            if [[ -f "$SCRIPT_DIR/agents/codex/skills/$hook_skill/SKILL.md" ]]; then
                cp "$SCRIPT_DIR/agents/codex/skills/$hook_skill/SKILL.md" "$skills_base_dir/$hook_skill/SKILL.md"
            fi
        else
            curl -fsSL "$REPO/install/agents/codex/skills/$hook_skill/SKILL.md" \
                -o "$skills_base_dir/$hook_skill/SKILL.md" 2>/dev/null || true
        fi
    done
    print_success "Installed hook skills to $skills_base_dir/"

    # Install parallel library bundle (Node.js-compatible)
    # Satisfies: RT-8 (parallel library portability), T7 (Node.js bundle), B1 (feature parity)
    local lib_dir="$codex_config_dir/lib/parallel"
    mkdir -p "$lib_dir"
    if [[ -n "$LOCAL_INSTALL" ]]; then
        if [[ -f "$SCRIPT_DIR/lib/parallel/parallel.bundle.js" ]]; then
            cp "$SCRIPT_DIR/lib/parallel/parallel.bundle.js" "$lib_dir/parallel.bundle.js"
            print_success "Installed parallel library bundle to $lib_dir/"
        fi
    else
        curl -fsSL "$REPO/install/lib/parallel/parallel.bundle.js" \
            -o "$lib_dir/parallel.bundle.js" 2>/dev/null && \
            print_success "Installed parallel library bundle to $lib_dir/" || true
    fi

    # Merge Manifold config into Codex config.toml
    # Satisfies: RT-6 (idempotent configuration)
    local config_path="$codex_config_dir/config.toml"
    if command -v bun &> /dev/null; then
        if [[ -n "$LOCAL_INSTALL" ]]; then
            bun run "$SCRIPT_DIR/lib/config-merger.ts" codex "$config_path" 2>/dev/null || true
        fi
    fi

    # Inject schema reference into AGENTS.md
    inject_schema_reference "$codex_config_dir" "AGENTS.md"
}

# Main installation
# Satisfies: B1 (all 4 agents), RT-2 (agent detection), RT-3 (per-agent routing)
main() {
    print_banner

    local installed=0
    local claude_dir=""
    local amp_dir=""
    local gemini_dir=""
    local codex_dir=""

    # Detect available agents
    print_step "Detecting AI coding agents..."
    echo ""

    # Check Claude Code
    if claude_dir=$(detect_claude_code); then
        print_success "Claude Code detected: $claude_dir"
    else
        print_warning "Claude Code not found"
    fi

    # Check AMP
    if amp_dir=$(detect_amp); then
        print_success "AMP detected: $amp_dir"
    else
        print_warning "AMP not found"
    fi

    # Check Gemini CLI
    if gemini_dir=$(detect_gemini); then
        print_success "Gemini CLI detected: $gemini_dir"
    else
        print_warning "Gemini CLI not found"
    fi

    # Check Codex CLI
    if codex_dir=$(detect_codex); then
        print_success "Codex CLI detected: $codex_dir"
    else
        print_warning "Codex CLI not found"
    fi

    echo ""

    # Abort if no agents found
    if [[ -z "$claude_dir" && -z "$amp_dir" && -z "$gemini_dir" && -z "$codex_dir" ]]; then
        print_error "No supported AI agents found!"
        echo ""
        echo "Manifold requires one of:"
        echo "  - Claude Code (https://claude.ai/code)"
        echo "  - AMP (https://amp.dev)"
        echo "  - Gemini CLI (https://github.com/google-gemini/gemini-cli)"
        echo "  - Codex CLI (https://github.com/openai/codex)"
        echo ""
        exit 1
    fi

    # Install to Claude Code (native .md commands)
    if [[ -n "$claude_dir" ]]; then
        install_manifold_native "$claude_dir" "Claude Code" "CLAUDE.md"
        ((installed++))
    fi

    # Install to AMP (native .md commands, same as Claude Code)
    if [[ -n "$amp_dir" ]]; then
        install_manifold_native "$amp_dir" "AMP" "CLAUDE.md"
        ((installed++))
    fi

    # Install to Gemini CLI (translated .toml commands)
    if [[ -n "$gemini_dir" ]]; then
        install_manifold_gemini "$gemini_dir"
        ((installed++))
    fi

    # Install to Codex CLI (translated SKILL.md files)
    if [[ -n "$codex_dir" ]]; then
        install_manifold_codex "$codex_dir"
        ((installed++))
    fi

    echo ""

    # Install CLI binary (optional but recommended)
    print_step "Installing CLI binary..."
    local platform
    platform=$(detect_platform)
    print_success "Detected platform: $platform"

    local cli_installed=0
    if install_cli "$platform"; then
        cli_installed=1
    fi

    echo ""
    echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
    if [[ $cli_installed -eq 1 ]]; then
        echo -e "${GREEN}  Manifold installed: $installed agent(s) + CLI binary${NC}"
    else
        echo -e "${GREEN}  Manifold installed successfully to $installed agent(s)!${NC}"
    fi
    echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "${BOLD}AI Agent Commands:${NC}"
    echo ""
    echo "  /manifold:m0-init my-feature        # Initialize manifold"
    echo "  /manifold:m1-constrain my-feature   # Discover constraints"
    echo "  /manifold:m2-tension my-feature     # Surface conflicts"
    echo "  /manifold:m3-anchor my-feature      # Backward reasoning"
    echo "  /manifold:m4-generate my-feature    # Create all artifacts"
    echo "  /manifold:m6-integrate my-feature   # Wire artifacts together"
    echo "  /manifold:m5-verify my-feature      # Validate constraints"
    echo "  /manifold:m-status                  # Show current state"
    echo ""
    echo -e "${BOLD}Supported Agents:${NC}"
    [[ -n "$claude_dir" ]] && echo "  Claude Code  — native .md commands in ~/.claude/commands/"
    [[ -n "$amp_dir" ]]    && echo "  AMP          — native .md commands in ~/.amp/commands/"
    [[ -n "$gemini_dir" ]] && echo "  Gemini CLI   — .toml commands in ~/.gemini/commands/"
    [[ -n "$codex_dir" ]]  && echo "  Codex CLI    — SKILL.md files in ~/.agents/skills/"
    echo ""
    echo -e "${BOLD}Parallel Execution:${NC}"
    echo "  /manifold:parallel \"task1\" \"task2\"  # Execute tasks in parallel worktrees"
    echo ""
    if [[ $cli_installed -eq 1 ]]; then
        echo -e "${BOLD}CLI Commands (fast, deterministic, no AI):${NC}"
        echo ""
        echo "  manifold status [feature]     # Show manifold state (<100ms)"
        echo "  manifold validate [feature]   # Validate schema"
        echo "  manifold init <feature>       # Initialize new manifold"
        echo "  manifold verify [feature]     # Verify artifacts exist"
        echo ""
    fi
    echo "Documentation: https://github.com/dhanesh/manifold"
    echo ""
}

# Validate installation
validate_installation() {
    local base_dir="$1"
    local agent_name="$2"
    local errors=0

    echo ""
    print_step "Validating $agent_name installation..."

    # Check skill file
    if [[ ! -f "$base_dir/skills/manifold/SKILL.md" ]]; then
        print_error "Missing: skills/manifold/SKILL.md"
        ((errors++))
    else
        print_success "Found: skills/manifold/SKILL.md"
    fi

    # Check command files
    for cmd_file in "${COMMAND_FILES[@]}"; do
        if [[ ! -f "$base_dir/commands/$cmd_file" ]]; then
            print_error "Missing: commands/$cmd_file"
            ((errors++))
        else
            print_success "Found: commands/$cmd_file"
        fi
    done

    # Check parallel library files
    for lib_file in "${PARALLEL_LIB_FILES[@]}"; do
        if [[ ! -f "$base_dir/lib/parallel/$lib_file" ]]; then
            print_error "Missing: lib/parallel/$lib_file"
            ((errors++))
        else
            print_success "Found: lib/parallel/$lib_file"
        fi
    done

    # Check hooks
    local hooks=("manifold-context.ts" "auto-suggester.ts")
    for hook_file in "${hooks[@]}"; do
        if [[ ! -f "$base_dir/hooks/$hook_file" ]]; then
            print_error "Missing: hooks/$hook_file"
            ((errors++))
        else
            print_success "Found: hooks/$hook_file"
        fi
    done

    # Summary
    echo ""
    if [[ $errors -eq 0 ]]; then
        print_success "$agent_name installation validated: All files present"
        return 0
    else
        print_error "$agent_name installation has $errors missing file(s)"
        return 1
    fi
}

# Validate Gemini CLI installation
# Satisfies: RT-10 (health check)
validate_gemini_installation() {
    local base_dir="$1"
    local errors=0

    echo ""
    print_step "Validating Gemini CLI installation..."

    # Check .toml command files
    local toml_count=0
    if [[ -d "$base_dir/commands" ]]; then
        toml_count=$(ls "$base_dir/commands"/*.toml 2>/dev/null | wc -l | tr -d ' ')
    fi
    if [[ "$toml_count" -gt 0 ]]; then
        print_success "Found: $toml_count .toml command files"
    else
        print_error "Missing: .toml command files in $base_dir/commands/"
        ((errors++))
    fi

    # Check parallel library bundle
    if [[ -f "$base_dir/lib/parallel/parallel.bundle.js" ]]; then
        print_success "Found: parallel library bundle"
    else
        print_warning "Missing: lib/parallel/parallel.bundle.js (parallel execution won't work)"
    fi

    # Check GEMINI.md
    if [[ -f "$base_dir/GEMINI.md" ]] && grep -q "Manifold Schema" "$base_dir/GEMINI.md" 2>/dev/null; then
        print_success "Found: GEMINI.md with schema reference"
    else
        print_warning "GEMINI.md missing or lacks schema reference"
    fi

    echo ""
    if [[ $errors -eq 0 ]]; then
        print_success "Gemini CLI installation validated"
        return 0
    else
        print_error "Gemini CLI installation has $errors issue(s)"
        return 1
    fi
}

# Validate Codex CLI installation
# Satisfies: RT-10 (health check)
validate_codex_installation() {
    local base_dir="$1"
    local skills_dir="$HOME/.agents/skills"
    local errors=0

    echo ""
    print_step "Validating Codex CLI installation..."

    # Check SKILL.md skill directories
    local skill_count=0
    if [[ -d "$skills_dir" ]]; then
        skill_count=$(ls -d "$skills_dir"/manifold-*/SKILL.md 2>/dev/null | wc -l | tr -d ' ')
    fi
    if [[ "$skill_count" -gt 0 ]]; then
        print_success "Found: $skill_count Codex skill directories"
    else
        print_error "Missing: Codex skills in $skills_dir/"
        ((errors++))
    fi

    # Check hook skills
    for hook_skill in "manifold-context" "manifold-suggest"; do
        if [[ -f "$skills_dir/$hook_skill/SKILL.md" ]]; then
            print_success "Found: $hook_skill skill"
        else
            print_warning "Missing: $hook_skill skill"
        fi
    done

    # Check parallel library bundle
    if [[ -f "$base_dir/lib/parallel/parallel.bundle.js" ]]; then
        print_success "Found: parallel library bundle"
    else
        print_warning "Missing: lib/parallel/parallel.bundle.js (parallel execution won't work)"
    fi

    # Check AGENTS.md
    if [[ -f "$base_dir/AGENTS.md" ]] && grep -q "Manifold Schema" "$base_dir/AGENTS.md" 2>/dev/null; then
        print_success "Found: AGENTS.md with schema reference"
    else
        print_warning "AGENTS.md missing or lacks schema reference"
    fi

    echo ""
    if [[ $errors -eq 0 ]]; then
        print_success "Codex CLI installation validated"
        return 0
    else
        print_error "Codex CLI installation has $errors issue(s)"
        return 1
    fi
}

# Run validation for all detected agents
# Satisfies: RT-10 (health check), O1 (installation verification)
run_validation() {
    local validated=0
    local failed=0

    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║${NC}  ${BOLD}Manifold Installation Validation${NC}                      ${CYAN}║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════╝${NC}"
    echo ""

    # Validate Claude Code
    if [[ -d "$HOME/.claude" ]]; then
        if validate_installation "$HOME/.claude" "Claude Code"; then
            ((validated++))
        else
            ((failed++))
        fi
    fi

    # Validate AMP
    if [[ -d "$HOME/.amp" ]]; then
        if validate_installation "$HOME/.amp" "AMP"; then
            ((validated++))
        else
            ((failed++))
        fi
    fi

    # Validate Gemini CLI
    if [[ -d "$HOME/.gemini" ]]; then
        if validate_gemini_installation "$HOME/.gemini"; then
            ((validated++))
        else
            ((failed++))
        fi
    fi

    # Validate Codex CLI
    if [[ -d "$HOME/.codex" ]]; then
        if validate_codex_installation "$HOME/.codex"; then
            ((validated++))
        else
            ((failed++))
        fi
    fi

    echo ""
    echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
    if [[ $failed -eq 0 ]]; then
        echo -e "${GREEN}  Validation complete: $validated agent(s) verified${NC}"
    else
        echo -e "${YELLOW}  Validation complete: $validated passed, $failed failed${NC}"
    fi
    echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
    echo ""
}

# Handle local install mode
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "$SCRIPT_DIR/manifold/SKILL.md" && -d "$SCRIPT_DIR/commands" ]]; then
    LOCAL_INSTALL=1
fi

# Check for validation flag
if [[ "$1" == "--validate" || "$1" == "-v" ]]; then
    run_validation
    exit 0
fi

main "$@"

# Run validation after installation
run_validation
