#!/usr/bin/env bun
/**
 * Build the manifold visualiser PWA and embed every output asset into a
 * generated TypeScript module the CLI binary serves at runtime.
 *
 * Pipeline:
 *   1. cd cli/web && bun install && bun run build  (Vite → cli/web/dist)
 *   2. Walk cli/web/dist recursively, hashing + collecting every file
 *   3. Emit cli/lib/embedded-assets.generated.ts with a Map<path, asset>
 *
 * Satisfies: RT-1 (embedded asset bundle), RT-10 (Vite chunking),
 *            T1 (no CDN — every asset embedded), O3 (cache namespace
 *            keyed on CLI binary version, set in vite.config.ts).
 */

import { readdirSync, readFileSync, statSync, writeFileSync, existsSync } from 'fs';
import { dirname, join, posix, sep, extname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { spawnSync } from 'child_process';

// Resolve repo paths relative to this file so the script works from any cwd.
const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const CLI_WEB = join(REPO_ROOT, 'cli', 'web');
const DIST = join(CLI_WEB, 'dist');
const OUT = join(REPO_ROOT, 'cli', 'lib', 'embedded-assets.generated.ts');

const CONTENT_TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.mjs': 'application/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.webp': 'image/webp',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.webmanifest': 'application/manifest+json',
  '.ico': 'image/x-icon',
  '.txt': 'text/plain; charset=utf-8',
  '.map': 'application/json; charset=utf-8',
};

const IMMUTABLE_DIRS = ['/assets/'];

interface Asset {
  urlPath: string;
  filePath: string;
  contentType: string;
  immutable: boolean;
}

function walk(dir: string, base: string = dir): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const abs = join(dir, entry);
    const st = statSync(abs);
    if (st.isDirectory()) out.push(...walk(abs, base));
    else out.push(abs);
  }
  return out;
}

function ensureBuilt(): void {
  if (!existsSync(DIST)) {
    console.error(
      `cli/web/dist not found. Building the web project first…`,
    );
    const install = spawnSync('bun', ['install'], { cwd: CLI_WEB, stdio: 'inherit' });
    if (install.status !== 0) process.exit(install.status ?? 1);
    const build = spawnSync('bun', ['run', 'build'], { cwd: CLI_WEB, stdio: 'inherit' });
    if (build.status !== 0) process.exit(build.status ?? 1);
  }
}

function toAsset(filePath: string): Asset {
  const rel = filePath.slice(DIST.length).split(sep).join(posix.sep);
  const urlPath = rel.startsWith('/') ? rel : `/${rel}`;
  const ext = extname(urlPath).toLowerCase();
  return {
    urlPath,
    filePath,
    contentType: CONTENT_TYPES[ext] ?? 'application/octet-stream',
    immutable: IMMUTABLE_DIRS.some((p) => urlPath.startsWith(p)),
  };
}

function emitModule(assets: Asset[]): void {
  const lines: string[] = [
    '/**',
    ' * Embedded Assets — auto-generated by `scripts/build-web.ts`.',
    ' * DO NOT EDIT BY HAND.',
    ' *',
    ' * Satisfies: RT-1 (embedded asset bundle in CLI binary).',
    ' */',
    '',
    'import type { EmbeddedAssetMap } from \'./embedded-assets.js\';',
    '',
    'function decode(b64: string): Uint8Array {',
    '  const bin = atob(b64);',
    '  const out = new Uint8Array(bin.length);',
    '  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);',
    '  return out;',
    '}',
    '',
    'export const EMBEDDED_ASSETS: EmbeddedAssetMap = new Map([',
  ];

  for (const asset of assets) {
    const data = readFileSync(asset.filePath);
    const b64 = data.toString('base64');
    lines.push(
      `  [${JSON.stringify(asset.urlPath)}, { contentType: ${JSON.stringify(asset.contentType)}, body: decode(${JSON.stringify(b64)}), immutable: ${asset.immutable} }],`,
    );
  }

  lines.push(']);', '');
  writeFileSync(OUT, lines.join('\n'));
}

function main(): void {
  ensureBuilt();
  const files = walk(DIST);
  const assets = files.map(toAsset);
  emitModule(assets);
  const total = assets.reduce((acc, a) => acc + statSync(a.filePath).size, 0);
  console.log(
    `Embedded ${assets.length} files (${(total / 1024).toFixed(1)} KB) into ${OUT}`,
  );
}

main();
